POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam",
  "name": "Adam",
  "password": "adam_567",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam",
  "password": "adam_567"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard@123",
  "newPassword": "richard@1234"
}
###